import os
# print(os.getcwd())
# print(os.chdir('C:\QA Automation Pyton\my_homework'))
# print(os.getcwd())
# os.mkdir('Test')
# os.makedirs('hm_6\Test')
# os.removedirs('C:\QA Automation Pyton\my_homework\hm_6\hm_6\Test')
# os.rmdir('C:\QA Automation Pyton\my_homework\hm_6\Test')
# os.rename('task_one_two.py','C:\QA Automation Pyton\my_homework\hm_6')
# print(os.stat('C:\QA Automation Pyton\my_homework\hm2.py'))
# print(os.environ)
# print(os.environ.get('C:\QA Automation Pyton\my_homework'))
# join_path = os.path.join('C:\QA Automation Pyton\my_homework\join1','C:\QA Automation Pyton\my_homework\join2')
# print(join_path)
# print(os.path.split('C:\QA Automation Pyton\my_homework\my_gm5.py'))
# print(os.path.basename('C:\QA Automation Pyton\my_homework\my_gm5.py'))
# print(os.path.dirname('C:\QA Automation Pyton\my_homework\my_gm5.py'))
